name: AWS - publish docker image to ECR

on:
  workflow_dispatch:
    inputs:
      workingdir:
        description: 'Working directory for the Dockerfile'
        required: true
        default: './dotnet/console-app/ConsoleApp'
      aws_region:
        description: 'AWS Region to login to'
        required: true
        default: 'us-west-2'
      ecr_repo:
        description: 'ECR repo to publish to'
        required: true
        default: 'none'


jobs:
  build_and_push:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.workingdir }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ github.event.inputs.ecr_repo }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG