name: Choose branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "The branch to use for checkout"
        required: false
        default: "main"

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Branch ENV var
        run: echo "BRANCH=${{ github.event.inputs.branch || 'main' }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH }}

      - name: Verify
        run: echo "Branch = ${{ env.BRANCH }}"
