name: dotnet build and test by working dir

on:
  workflow_dispatch:
    inputs:
      workingdir:
        description: 'Working directory for the dotnet solution'
        required: true
        default: './dotnet/libs-and-tests'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.event.inputs.workingdir }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
