name: Environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment'
        required: true
        default: 'production'


jobs:
  test-env:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Verify
        run: |
          echo "ENVIRONMENT_DEPENDENT_VAR (env var): ${{ vars.ENVIRONMENT_DEPENDENT_VAR }}" | sed 's/./& /g'
          echo "ENVIRONMENT_DEPENDENT (secret): ${{ secrets.ENVIRONMENT_DEPENDENT }}" | sed 's/./& /g'
          echo "NORMAL_VAR (var): ${{ vars.NORMAL_VAR }}"
