name: Needs output

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag'
        required: true
        default: 'some_tag'

jobs:
  job1:

    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.set-tag.outputs.tag_name }}

    steps:
      - name: Set value
        id: set-tag
        run: |
          echo "TAG_NAME=${{ inputs.tag_name }}" >> $GITHUB_ENV
          echo "tag_name=${{ inputs.tag_name }}" >> $GITHUB_OUTPUT
      - name: Echo env var
        run: |
          echo "ENV VAR = ${{ env.TAG_NAME }}"

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
      - name: Echo value
        run: |
          # Write the output from job1
          echo ${{ needs.job1.outputs.tag_name }}
